#use_frameworks!

workspace 'SyncKit.xcworkspace'

target 'SyncKitCoreDataExample' do
	
  project 'SyncKitCoreDataExample'
  platform :ios, '10.0'

  pod 'SyncKit/CoreData', :path => '../'

  target 'SyncKitCoreDataExampleTests' do
    inherit! :search_paths

	pod 'OCMock', '~> 3.4'
    
  end
end

target 'SyncKitRealmExample' do

	project 'SyncKitRealmExample'
 	platform :ios, '10.0'

	pod 'SyncKit/Realm', :path => '../'

	pod 'Realm', '~> 3.0'

	target 'SyncKitRealmExampleTests' do
		inherit! :search_paths
	end
end

target 'SyncKitRealmExampleTodayExtension' do

	project 'SyncKitRealmExample'
	platform :ios, '10.0'
	
	pod 'SyncKit/Realm', :path => '../'

	pod 'Realm', '~> 3.0'
end
