use_frameworks!

workspace 'SyncKitCoreData.xcworkspace'
project 'SyncKitCoreDataExample/SyncKitCoreDataExample'

target 'SyncKitCoreDataExample' do
	
  platform :ios, '10.0'

  pod 'SyncKit/CoreData', :path => '../../'

  target 'SyncKitCoreDataExampleTests' do
    inherit! :search_paths
  end
end

target 'WatchApp' do
	project 'WatchApp/WatchApp'
	platform :watchos, '3.0'
	pod 'SyncKit/CoreData', :path => '../../'
end