use_frameworks!
inhibit_all_warnings!

workspace 'SyncKitRealmSwift.xcworkspace'

target 'SyncKitRealmSwiftExample' do

	project 'SyncKitRealmSwiftExample'
 	platform :ios, '10.0'

	pod 'SyncKit/RealmSwift', :path => '../../'

	pod 'RealmSwift'

	target 'SyncKitRealmSwiftExampleTests' do
		inherit! :search_paths
	end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
