use_frameworks!

workspace 'SyncKitRealm.xcworkspace'
project 'SyncKitRealmExample/SyncKitRealmExample'

target 'SyncKitRealmExample' do
	
  platform :ios, '10.0'

  pod 'Realm'
  pod 'SyncKit/Realm', :path => '../../'

  target 'SyncKitRealmExampleTests' do
    inherit! :search_paths
  end
end

target 'SyncKitRealmExampleTodayExtension' do

#	project 'SyncKitRealmExample'
	platform :ios, '10.0'
	
	pod 'SyncKit/Realm', :path => '../../'

	pod 'Realm'
end

post_install do |installer|
     installer.pods_project.targets.each do |target|
           target.build_configurations.each do |config|
                 config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
           end
     end
 end