use_frameworks!

workspace 'SyncKitRealm.xcworkspace'
project 'SyncKitRealmExample/SyncKitRealmExample'

target 'SyncKitRealmExample' do
	
  platform :ios, '10.0'

  pod 'Realm'
  pod 'SyncKit/Realm', :path => '../../'

  target 'SyncKitRealmExampleTests' do
    inherit! :search_paths
  end
end

target 'SyncKitRealmExampleTodayExtension' do

#	project 'SyncKitRealmExample'
	platform :ios, '10.0'
	
	pod 'SyncKit/Realm', :path => '../../'

	pod 'Realm'
end