use_frameworks!
inhibit_all_warnings!

workspace 'SyncKitRealmSwift.xcworkspace'

target 'SyncKitRealmSwiftExample' do

	project 'SyncKitRealmSwiftExample'
 	platform :ios, '10.0'

	pod 'SyncKit/RealmSwift', :path => '../../'

	pod 'RealmSwift', '~> 3.0'

	target 'SyncKitRealmSwiftExampleTests' do
		inherit! :search_paths
	end
end

