use_frameworks!

workspace 'SyncKitRealmSwift.xcworkspace'
project 'SyncKitRealmSwiftExample/SyncKitRealmSwiftExample'

target 'SyncKitRealmSwiftExample' do
	
  platform :ios, '10.0'

  pod 'RealmSwift'
  pod 'SyncKit/RealmSwift', :path => '../../'

  target 'SyncKitRealmSwiftExampleTests' do
    inherit! :search_paths
  end
end
